### ISSUE TITLE
Automatically remove _acme-challenge DNS TXT entries

### ISSUE THREAD

**Issue by IsaacWG** [miigotu/certbot-dns-godaddy#3]
Hi,

This plugin is working great, however I have noticed that it leaves behind the "_acme-challenge" DNS TXT entries. Would it be possible to automatically remove these entries after certbot is finished?

Thanks!

**Comment by parthjoshi-pc** [comment]
Tried this plugin and found the same problem. I understand the GoDaddy API does not make deleting DNS records easy since you have to basically update all the DNS records for a domain to do so. I can see the plugin makes certain API requests during the "cleaning up challenges" step of the run by enabling detailed logging using the `-vvv` switch when running certbot:

```
Calling registered functions
Cleaning up challenges
Starting new HTTPS connection (1): api.godaddy.com:443
https://api.godaddy.com:443 "GET /v1/domains/privatecircle.co HTTP/1.1" 200 1645
Starting new HTTPS connection (1): api.godaddy.com:443
https://api.godaddy.com:443 "GET /v1/domains/privatecircle.co/records HTTP/1.1" 200 17609
Starting new HTTPS connection (1): api.godaddy.com:443
https://api.godaddy.com:443 "PUT /v1/domains/privatecircle.co/records HTTP/1.1" 200 0
delete_records: _acme-challenge.random.privatecircle.co vKRvATIv9dbTQXYnNkU7VlyGGF6-8fvUSWDgLYM72OQ None
```

However, the DNS record does not actually get cleaned up in GoDaddy. Haven't dug deep enough to determine if this is an issue with this plugin, lexicon or the GoDaddy API itself.
